src/main/java/pl/java/biniek/web/beans/admin/AdminListViewBean.java
//ok
package pl.java.biniek.web.beans.admin;

import pl.java.biniek.web.beans.controlers.UzerController;
import java.io.Serializable;
import java.util.List;
import javax.inject.Named;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import pl.java.biniek.exception.interceptor.frontend.BinderPageBean;
import pl.java.biniek.model.Administrator;

@Named
@ViewScoped
@BinderPageBean
public class AdminListViewBean implements Serializable {

    @Inject
    UzerController uzerControler;

    public UzerController getUzerControler() {
        return uzerControler;
    }

  
       
   //w zasadzie dostęp do listy organizatorów to może mieć każdy
    public List<Administrator> getAllAdministrator(){
        return uzerControler.getAllAdmins();
    }
}

src/main/java/pl/java/biniek/web/beans/applicationcontroller/AplicationControlerBean.java
package pl.java.biniek.web.beans.applicationcontroller;

//package org.primefaces.showcase.view.message;
import java.io.Serializable;
import javax.inject.Named;
import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import pl.java.biniek.exception.interceptor.frontend.BinderPageBean;
import pl.java.biniek.exceptions.BasicApplicationException;
import pl.java.biniek.web.beans.controlers.AplicationController;
import pl.java.biniek.web.beans.controlers.TestButtonsController;
import pl.java.biniek.web.beans.controlers.UzerController;
//import pl.java.biniek.web.themes.Theme;

@RequestScoped
@Named
@BinderPageBean
public class AplicationControlerBean implements Serializable {

    @Inject
    UzerController uzercontroller;
    @Inject
    AplicationController aplicationController;

    //Theme theme;
    public void resetSession() throws Exception {
     AplicationController.resetSession();
      
      
    }

    public String getName() {

        return uzercontroller.getUzersName();
    }

    public String starttest() throws Throwable {
        return uzercontroller.test();
        // return null;
    }



    public boolean getTestButtons() {
        return TestButtonsController.isTestButtons();
    }

    public String editUzer() throws BasicApplicationException {
        return uzercontroller.editLoggedUzer();
    }

}

src/main/java/pl/java/biniek/web/beans/controlers/UzerController.java
//ok

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.java.biniek.web.beans.controlers;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;

import pl.java.biniek.endpoints.UzerEndPoint;
import pl.java.biniek.exceptions.BasicApplicationException;
import pl.java.biniek.exceptions.WrongUzerApplicationException;
import pl.java.biniek.model.Administrator;
import pl.java.biniek.model.Organiser;
import pl.java.biniek.model.Uzer;
import pl.java.biniek.exception.interceptor.frontend.BinderController;
import pl.java.biniek.exception.interceptor.frontend.BinderPageBean;
import pl.java.biniek.model.Runner;

@Named
@SessionScoped
@BinderController
//@Interceptors(LoggingInterceptorForController.class)
public class UzerController implements Serializable {

    @EJB
    UzerEndPoint uzerEndPoint;

    private Runner editetRunner;

    private Runner viewedRunner;

    private Organiser editetOrganiser;

    private Organiser viewedOrganiser;

    public Organiser getViewedOrganiser() {
        return viewedOrganiser;
    }

    public void setViewedOrganiser(Organiser viewedOrganiser) {
        this.viewedOrganiser = viewedOrganiser;
    }

    public int birthYear(Date date) {
        LocalDate ld;
        LocalDate lDate = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        return lDate.getYear();

    }

  
    public String getSex(boolean isMale) {// uzupelnic internacjonalizacje
        if (isMale) {
            return AplicationController.getInternationalMessage("orms.runner.sexmale");
        }
        return AplicationController.getInternationalMessage("forms.runner.sexfemale");
    }
// getbirthyare

    public List<Organiser> getAllOrganisers() {
        return uzerEndPoint.getAllOrganisers();
    }

    public List<Administrator> getAllAdmins() {
        return uzerEndPoint.getAllAdmins();
    }

    public Organiser getEditetOrganiser() {
        return editetOrganiser;
    }

    public void setEditetOrganiser(Organiser editetOrganiser) {
//        if (editetOrganiser != null) {
//            this.editetOrganiser = (Organiser) uzerEndPoint.findUzerByEmail(editetOrganiser.getEmail());
//        } else {
        this.editetOrganiser = editetOrganiser;
//        }
    }

    public String saveNew(Uzer uzer) throws BasicApplicationException {
        uzerEndPoint.createUzer(uzer);
        AplicationController.showInfoSuccesMessage(null);
        return "registerUser-return";

    }

    public String saveNew(Administrator admin) throws BasicApplicationException {

        uzerEndPoint.createAdministrator(admin);// 
        AplicationController.showInfoSuccesMessage("");
        return "registerUser-return";

    }

    public String saveEditedOrganiser(Organiser org) throws BasicApplicationException {

        this.saveAfterEdit(org);
        AplicationController.showInfoSuccesMessage(null);
        this.setViewedOrganiser((Organiser) this.getUzerByEmail(org.getEmail()));
        this.setEditetOrganiser(null);
       
        return "organiserDetails";
    }

    public void saveAfterEdit(Organiser org) throws BasicApplicationException {

        uzerEndPoint.saveAfterEdit(org);
    }

    public String saveEditedRunner(Runner run) throws BasicApplicationException {
        //    Runner run = editetRunner;

        //  this.setEditetRunner(null);//domosc faces
        this.saveAfterEdit(run);
        AplicationController.showInfoSuccesMessage(null);

        this.setViewedRunner((Runner) this.getUzerByEmail(run.getEmail()));
        this.setEditetRunner(null);
        return "runnerDetails";

    }

    public void saveAfterEdit(Runner runer) throws BasicApplicationException {
        uzerEndPoint.saveAfterEdit(runer);
    }


    public String delete(Organiser organiserForDelete) throws BasicApplicationException {
        this.removeUzer(organiserForDelete);
        return "listOfOrganisers";

    }

    public String getOutputDate(Date date) {

        SimpleDateFormat outDate = new SimpleDateFormat("yyyy-mm-dd");
        return outDate.format(date);

    }

    @BinderPageBean
    public Runner getViewedRunner() {
        return viewedRunner;
    }

    @BinderPageBean
    public void setViewedRunner(Runner viewedRunner) {
        this.viewedRunner = viewedRunner;
    }

    public List<Runner> getAllRunners() throws WrongUzerApplicationException {

        if (getLoggedUser() instanceof Administrator) {
            return uzerEndPoint.getAllRunners();
        } else {
            throw new WrongUzerApplicationException();
        }
    }



    public Runner getEditetRunner() {
        return editetRunner;
    }
//@BinderPageBean

    public void setEditetRunner(Runner editetRunner) {
        this.editetRunner = editetRunner;
    }

    ///////////////////////////////////////////////////////////////////
    ///////// przeuniete z pagebeanow
    ///////////////////////////////////////////////////////////////////
    public String saveNew(Runner runner) throws BasicApplicationException {
        uzerEndPoint.createUzer(runner);
        AplicationController.showInfoSuccesMessage("");
        return "registerUser-return";

    }


    public void removeUzer(Uzer uzer) throws BasicApplicationException {
        uzerEndPoint.remove(uzer);
    }

    public String deleteRunner(Runner runnerForDelete) throws BasicApplicationException {
        this.removeUzer(runnerForDelete);
        return "listOfRunners";
    }

    public Uzer getUzerByEmail(String email) {
        return uzerEndPoint.findUzerByEmail(email);

    }

    public Uzer getLoggedUser() {
        return uzerEndPoint.getLoggedUser();
    }
//!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!11

    public String deleteViewedOrganiser(Organiser org) throws BasicApplicationException {
        this.removeUzer(org);
        this.setViewedOrganiser(null);
        AplicationController.showInfoSuccesMessage(null);

        //  this.setViewedOrganiser(null);
        return "listOfOrganisers";
    }

    public String deleteViewedRunner(Runner runer) throws BasicApplicationException {
        //Runner run = viewedRunner;
        this.removeUzer(runer);
        this.setViewedRunner(null);
        AplicationController.showInfoSuccesMessage(null);

        return "listOfRunners";

    }

    public String editLoggedUzer() throws BasicApplicationException {
        Uzer loggedUzer = getLoggedUser();
        if (loggedUzer instanceof Runner) {
            this.setEditetRunner((Runner) loggedUzer);
            return "/runnerEdit";
        } else if (loggedUzer instanceof Organiser) {
            this.setEditetOrganiser((Organiser) loggedUzer);
            return "/organiserEdit";
        }
        throw new WrongUzerApplicationException();

    }

    /**
     * metoda zwracająca mozliwośc testowania pierdół, interceptorów itp
     * controlera in vivo
     *
     */
    @Deprecated
    public String test() throws Throwable {
        // throw new Error("test");
        //String email="run1@run1.pl";
  
        return null;
    }

    public String getUzersName() {

        if (null != FacesContext.getCurrentInstance().getExternalContext().getRemoteUser()) {
            //  setLoggedUzer();

            return this.getLoggedUser().getName();

        } else {
            return "";
        }
    }

    public String saveNewPasswordForLoggedUzer(String passwd) {
        uzerEndPoint.saveNewPasswordForLogged(passwd); //To change body of generated methods, choose Tools | Templates.
        AplicationController.showInfoSuccesMessage(null);
        return "index";
    }

    public boolean doesGivenEmailExists(String email) {

        return uzerEndPoint.checkEmailExistsInDB(email);

    }

//    @Deprecated
//    public List<Uzer> getAllUzers() {
//        return uzerEndPoint.getAllUzers();
//    }
}

src/main/java/pl/java/biniek/web/beans/courses/CourseDetailsBean.java
//ok podniesiono
/**
 * Autor Piotr ku pamięci Klasa CoursesPageViewBean  - klasa testowa  mozliwe rózne rozwiązania
 *  rozwiązanie odwołania się z xhtml do Kolekcji
 * albo poprzez nazwę klasy beana (jezeli nie damy mu nazwy @ManagedBean) czyli np poporzez
 * #{coursesPageViewBean.*}
 * jeżeli ma nazwę @ManagedBean(name = "listOfCourses")
 * #{listOfCourses.*}
 *
 * Tworzenie kolekcji rozwiązano na 2 sposoby
 * albo poprzez pobranie Kolekcji z endponta metodą Init opisaną   @PostConstruct,
 * #{*.coursesList}
 * albo wywołanie metody getAllCourses() która z wstrzyknietego endpointa zwraca kolekcje
 * #{*.allCourses}
 *
 */
package pl.java.biniek.web.beans.courses;

import pl.java.biniek.web.beans.controlers.CourseController;
import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import javax.inject.Inject;
import pl.java.biniek.exception.interceptor.frontend.BinderPageBean;
import pl.java.biniek.exception.interceptor.frontend.BinderStringToNull;
import pl.java.biniek.exceptions.BasicApplicationException;
import pl.java.biniek.model.Course;
import pl.java.biniek.model.Organiser;
import pl.java.biniek.model.Payment;
import pl.java.biniek.web.beans.controlers.UzerController;

@Named
@ViewScoped
@BinderPageBean
public class CourseDetailsBean implements Serializable {

    Course viewedCourse;
    boolean backNavigatedFromPrivateRuns=false;

    @Inject
    CourseController courseController;

    @Inject
    UzerController uzerControler;

    @PostConstruct
    public void init() {
        viewedCourse = courseController.findByID(courseController.getViewedCourse().getId());
        backNavigatedFromPrivateRuns=courseController.isBackNavigatedFromPrivateRuns();
    }

    public Course getViewedCourse() {
        return viewedCourse;
    }

    public CourseController getCourseControler() {
        return courseController;
    }

    public String editCourse() throws BasicApplicationException {

        return courseController.editViewedCourse(viewedCourse);
       
    }

    public String back() {

        courseController.setViewedCourse(null);
        if (backNavigatedFromPrivateRuns) {
            return "listOfMyCourses";
        }
        return "listOfCourses";
    }
    
    public String getOutputDateTime(Date date) {

        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd hh.mm");
         return formatter.format(date);
    }

    public String setViewOrganiser(Organiser org) {
        uzerControler.setViewedOrganiser(org);
        return "organiserDetails";


    }
@BinderStringToNull
    public Payment getCoursePaymentForLoggedRunner() throws BasicApplicationException {
        return courseController.getViewedCoursePaymentForLoggedRunner(viewedCourse);

    }
     public boolean isVievedCourseAfterCurrentDate() {
        Date currentDate = new Date();
        return getViewedCourse().getDateOfStart().before(currentDate);
    }


    public void signRunnerFor() throws BasicApplicationException {
        courseController.signLoggedRunnerForViewedCourse(viewedCourse);
        viewedCourse=courseController.findByID(viewedCourse.getId());//odswierzanie kursu
        
    }

    public void signRunnerOut() throws BasicApplicationException {
        courseController.signRunnerOut(viewedCourse);
        viewedCourse=courseController.findByID(viewedCourse.getId());
    }
    
    public String deleteViewedCourse() throws BasicApplicationException{
        courseController.setIsNavigatedFromMyCourses(backNavigatedFromPrivateRuns);
       return courseController.deleteCourse(viewedCourse);
        
    }
    
    public boolean  isAvalibleRunnersLimit(){
       return courseController.isAvalibleRunnersLimit(viewedCourse);
    }
        
    


}

src/main/java/pl/java/biniek/web/beans/courses/CourseWizard.java
//ok


package pl.java.biniek.web.beans.courses;

import pl.java.biniek.web.beans.controlers.CourseController;
import java.io.Serializable;
import java.util.Date;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import org.primefaces.event.FlowEvent;
import pl.java.biniek.exception.interceptor.frontend.BinderPageBean;
import pl.java.biniek.exception.interceptor.frontend.BinderStringToNull;
import pl.java.biniek.exceptions.BasicApplicationException;
import pl.java.biniek.model.Course;
import pl.java.biniek.web.beans.controlers.AplicationController;

//@ManagedBean
@ViewScoped
//@RequestScoped
@Named
@BinderPageBean

public class CourseWizard implements Serializable {

    @Inject
    CourseController courseController;
    
    @Inject
    AplicationController uzerController;

    private boolean skip;

    private Course course = new Course();

    public Course getCourse() {
        return course;
    }

    public void setCourse(Course course) {
        this.course = course;
    }


    public boolean isSkip() {
        return skip;
    }

    public void setSkip(boolean skip) {
        this.skip = skip;
    }
@BinderStringToNull
    public String onFlowProcess(FlowEvent event) {
        if(courseController.doesGivenNameExists(course.getName())){ //uzerController.doesGivenEmailExists(organiser.getEmail())
            AplicationController.showMessage("addCourse:name", "messages.constraint.namecourse");
            return "coursedetails";
        }
        if(courseController.doesGivenShortNameExists(course.getShortName())){ 
            AplicationController.showMessage("addCourse:shortName", "messages.constraint.namecourse");
            return "coursedetails";
        }
        if (skip) {
            skip = false;   //reset in case user goes back
            return "confirm";
        } else {
            return event.getNewStep();
        }
    }

    public Date getToday() {

        return new Date();
    }


    public String save()  throws BasicApplicationException{ 
      return  courseController.saveNew(course);
      
       
    }
}

src/main/webapp/courseEdit.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <body>

        <ui:composition template="./template.xhtml">

            <ui:define name="content">
                <h:form id="editCourse">
                    <p:growl id="growl" sticky="true" showDetail="true"/>

                    <h:panelGrid id="tableEdit" columns="3" cellpadding="5"  >
                        <f:facet name = "header" >
                            <h:outputText value = " ${msg['title.courseedit']}" />
                        </f:facet>

                        <h:outputText value="#{msg['forms.addcours.name']}* : " />
                        <h:inputText id="name"  value="#{courseEditBean.editedCourse.name}" required="true" label="Firstname"/>
                        <p:message for="name"/>      



                        <h:outputText value="#{msg['forms.addcours.shortname']}* : " />
                        <h:inputText id="shortname" value="#{courseEditBean.editedCourse.shortName}" required="true" label="Lastname"/>
                        <p:message for="shortname" />

                        <h:outputText value="#{msg['forms.addcours.distance']}* : " />
                        <p:inputNumber id="distance" value="#{courseEditBean.editedCourse.distance}" decimalPlaces="2" required="true"/>
                        <p:message for="distance" />


                        <p:outputLabel for="datetime" value="#{msg['forms.addcours.startday']}* : " />
                        <p:calendar id="datetime" value="#{courseEditBean.editedCourse.dateOfStart}" pattern="dd/MM/yyyy HH:mm" required="true" mindate="#{courseWizard.today}"/>
                        <p:message for="datetime" />

                        <p:outputLabel  value="#{msg['forms.addcours.runnerslimit']}* : " />
                        <p:inputNumber id="runlimit" value="#{courseEditBean.editedCourse.runnersLimit}" decimalPlaces="0" required="true"/>
                        <p:message for="runlimit" />
                        <p:outputLabel  value="#{msg['forms.addcours.cityofcours']}* : " />
                        <p:inputText id="citycours" value="#{courseEditBean.editedCourse.cityOfCours}" required="true"/>
                        <p:message for="citycours" />


                        <h:outputText value="#{msg['forms.addcours.descent']} " />
                        <p:inputNumber id="descent" value="#{courseEditBean.editedCourse.descent}"  decimalPlaces="0" 
                                       emptyValue="zero" thousandSeparator=" "/>
                        <p:message for="descent" />

                        <h:outputText value="#{msg['forms.addcours.climb']} " />
                        <p:inputNumber id="inputVal" value="#{courseEditBean.editedCourse.climb}" decimalPlaces="0" 
                                       emptyValue="zero" thousandSeparator=" "/>
                        <p:message for="inputVal" />



                        <h:outputText value="#{msg['forms.addcours.officeplace']}* : " />
                        <p:inputText id="coursecity" value="#{courseEditBean.editedCourse.cityOfRunOffice}" required="true">
                        </p:inputText>
                        <p:message for="coursecity"/>

                        <h:outputText value="#{msg['forms.addcours.officeaddress']}* : " />
                        <p:inputText id="courseoffice" value="#{courseEditBean.editedCourse.addressOfRunOffice}" required="true">
                        </p:inputText>
                        <p:message for="courseoffice"/>

                        <h:outputText value="#{msg['forms.email']}* : " />
                        <p:inputText id="coursemail" value="#{courseEditBean.editedCourse.email}" required="true" label="Email">
                        </p:inputText>
                        <h:message for="coursecity"/>

                        <h:outputText value="#{msg['forms.phone']}: "/>
                        <h:inputText  id="phone" value="#{courseEditBean.editedCourse.phone}" />
                        <p:message for="phone"/>

                        <h:outputText value="#{msg['forms.addcours.addinfo']}: " />
                        <p:inputText id="info" value="#{courseEditBean.editedCourse.info}"/>
                        <p:message for="info"/>



                    </h:panelGrid>
                    <h:panelGroup id="pnl"  style="margin-bottom:10px;" >
                        <p:commandButton value="#{msg['menu.courses.list']}" action="listOfCourses" immediate="true"/>
                        <p:commandButton id="save" value="#{msg['buttons.save']}" action="#{courseEditBean.save()}"/>
                    </h:panelGroup>
                    <p:blockUI block="pnl" trigger="save" />




                </h:form>
            </ui:define>
        </ui:composition>
        <h:form>
            <h:commandLink action="#{course.listSetup}" value="Show All Course Items"/>
        </h:form>
    </body>

</html>



<!--                        <h:outputText value="#{msg['forms.addcours.name']} "/>
   <p:inputText value="#{courseDetailsBean.courseControler.viewedCourse.name}" styleClass="outputLabel"/>

   <h:outputText value="#{msg['forms.addcours.shortname']} " />
   <p:inputText value="#{courseDetailsBean.courseControler.viewedCourse.shortName}" styleClass="outputLabel"/>


   <h:outputText value= "#{msg['forms.addcours.startday']} "/>
   <p:d value="#{courseDetailsBean.courseControler.viewedCourse.dateOfStart}" styleClass="outputLabel"/>

   <h:outputText value= "#{msg['forms.addcours.distance']} "/>
   <h:inputText value="#{courseDetailsBean.courseControler.viewedCourse.distance}" styleClass="outputLabel"/>

   <p:outputLabel  value="#{msg['forms.addcours.runnerslimit']} " />
   <h:inputText  value="#{courseDetailsBean.courseControler.viewedCourse.runnersLimit}"  />

   <p:outputLabel  value="#{msg['forms.addcours.cityofcours']} " />
   <p:inputText  value="#{courseDetailsBean.courseControler.viewedCourse.cityOfCours}" />


   <h:outputText value= "#{msg['forms.addcours.climb']} "/>
   <h:outputText value="#{courseDetailsBean.courseControler.viewedCourse.climb}" styleClass="outputLabel"/>


   <h:outputText value= "#{msg['forms.addcours.descent']} "/>
   <h:outputText value="#{courseDetailsBean.courseControler.viewedCourse.descent}" styleClass="outputLabel"/>


   <h:outputText value= "#{msg['forms.addcours.officeplace']} "/>
   <h:outputText value="#{courseDetailsBean.courseControler.viewedCourse.cityOfRunOffice}" styleClass="outputLabel"/>

   <h:outputText value= "#{msg['forms.addcours.officeaddress']} "/>
   <h:outputText value="#{courseDetailsBean.courseControler.viewedCourse.addressOfRunOffice}" styleClass="outputLabel"/>


   <h:outputText value= "#{msg['forms.addcours.addinfo']} "/>
   <h:outputText value="#{courseDetailsBean.courseControler.viewedCourse.info}" styleClass="outputLabel"/>


   <h:outputText value= "#{msg['forms.addcours.organiser']} "/>
   <h:outputText value="organizer" styleClass="outputLabel"/>

   <h:outputText value= "#{msg['forms.email']} "/>
   <h:outputText value="#{courseDetailsBean.courseControler.viewedCourse.email}" styleClass="outputLabel"/>

   <h:outputText value= "#{msg['forms.phone']} "/>
   <h:outputText value="#{courseDetailsBean.courseControler.viewedCourse.phone}" styleClass="outputLabel"/>


-->

src/main/webapp/listOfOrrganiserCourses.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <body>

        <ui:composition template="./template.xhtml">
            <ui:param name="pageBeanCourses" value="#{dtListOfOrgCourses}" />
            <ui:define name="content">
                <p>
                    <p:outputLabel value="#{msg['forms.listofuzercourses']} #{dtListOfOrgCourses.courseControler.organiser.organiserName}" />
                </p>
                <h:form>

                    <ui:include src="templateCoursesList.xhtml"/>

                </h:form>

            </ui:define>

        </ui:composition>

    </body>
</html>


  <!--<p:commandButton value="#{msg['buttons.registerrunner']}" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close" />-->


<!--

 


                        <f:facet name="paginatorTopLeft">
                            <p:commandButton type="button" icon="fa fa-sync" />
                        </f:facet>

                        <f:facet name="paginatorBottomRight">
                            <p:commandButton type="button" icon="fa fa-cloud-upload" />
                        </f:facet>-->

<!--                        <p:growl id="growl" showDetail="true" sticky="false" >
                            <p:autoUpdate />

                        </p:growl>-->
<!--<p:calendar value="#{iteratorCourse.dateOfStart}"  pattern="dd/MM/yyyy HH:mm" readonly=""/>-->

src/main/webapp/listOfParticipants.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <body>

        <ui:composition template="./template.xhtml">

            <ui:define name="content">

                <h:form>
                    <p:growl id="growl" showDetail="true" sticky="false" >
                        <p:autoUpdate />

                    </p:growl>
                    <h:outputText value=" #{msg['forms.registeredRunnersforcourse']} #{participantRunnerViewBean.course.name}" />


                    <p:dataTable id="runnerstable" var="iteratorRunner" value="#{participantRunnerViewBean.participantList}" rows="50"
                                 paginator="true"  paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                                 rowsPerPageTemplate="10,50,100">
                        <p:column headerText="#{msg['forms.registerrunner.fname']}">
                            <h:outputText value="#{iteratorRunner.firstName}" />
                        </p:column>

                        <p:column headerText="#{msg['forms.registerrunner.lname']}" >
                            <h:outputText value="#{iteratorRunner.lastName}" />
                        </p:column>


                        <p:column headerText="#{msg['forms.runner.birthyear']}">
                            <h:outputText value="#{iteratorRunner.birthYare}" />
                        </p:column>

                        <p:column headerText="#{msg['forms.registerrunner.sex']}">
                            <h:outputText value="#{msg['forms.runner.sexfemale']}" rendered="#{aplicationControlerBean.testButtons or !iteratorRunner.isMale}" />
                            <h:outputText value="#{msg['forms.runner.sexmale']}" rendered="#{aplicationControlerBean.testButtons or iteratorRunner.isMale}" />
                        </p:column>                        

                        <p:column headerText="#{msg['forms.payment']}" rendered="#{aplicationControlerBean.testButtons or participantRunnerViewBean.courseControler.viewedCourse.paymentRequired}">
                            <h:outputText value="#{msg['forms.payment.payed']}" rendered="#{aplicationControlerBean.testButtons or not iteratorRunner.payed}" />
                            <h:outputText value="#{msg['forms.payment.notpayed']}" rendered="#{aplicationControlerBean.testButtons or  iteratorRunner.payed}" />
                        </p:column>  
                    </p:dataTable>





                </h:form>
            </ui:define>

        </ui:composition>

    </body>
</html>